# Generated by Django 4.2.7 on 2023-11-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='debt_to_supplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Задолженность поставщику'),
        ),
    ]
